export const TOGGLE_OVERLAY_VISIBILITY = 'EventBus:TOGGLE_OVERLAY_VISIBILITY';

export const WALLET_CONNECTED = 'EventBus:WALLET_CONNECTED';
export const WALLET_DISCONNECTED = 'EventBus:WALLET_DISCONNECTED';

export const WALLET_LINKED = 'EventBus:WALLET_LINKED';