export const TOGGLE_OVERLAY_VISIBILITY = 'TOGGLE_OVERLAY_VISIBILITY';

export const WALLET_CONNECTED = 'WALLET_CONNECTED';
export const WALLET_DISCONNECTED = 'WALLET_DISCONNECTED';

export const WALLET_LINKED = 'WALLET_LINKED';

export const ON_PENDING_TRANSECTION = 'ON_PENDING_TRANSECTION';
export const ON_TRANSECTION_COMPLETE = 'ON_TRANSECTION_COMPLETE';

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';

export const ON_WALLET_USER_ACTION = 'ON_WALLET_USER_ACTION';

export const TRIGGER_WALLET_CONNECT = 'TRIGGER_WALLET_CONNECT';
export const ON_QUOTE_PRICE_UPDATE = 'ON_QUOTE_PRICE_UPDATE';